### ISSUE TITLE
Server Error for av16809682 

### ISSUE THREAD

**Issue by ApolloZhu** [LiulietLee/BilibiliCoverDownloader#2]
https://www.bilibili.com/video/av16809682

**Comment by LiulietLee** [comment]
应该是所有动画的封面都搞不来吧，b 站有海外限制。
不过这个问题好像已经解决过了来着……
手动 @Haut-Stone

**Comment by Haut-Stone** [comment]
是bilibili把错误页的代码改了一部分js，导致抓不到图片了，已解决。

**Comment by LiulietLee** [comment]
试了下似乎还不行呢，是还没更新 VPS 的代码么？

**Comment by Haut-Stone** [comment]
还没实装= =。等和别的bug一块清了

**Comment by Haut-Stone** [comment]
已经实装了，可以去看看了

**Comment by LiulietLee** [comment]
OK
